// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sub_categories.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubCategory = `-- name: CreateSubCategory :one
INSERT INTO sub_categories (id, created_at, updated_at, name, slug, description, is_active, category_id)
VALUES ($1, NOW(), NOW(), $2, $3, $4, $5, $6) RETURNING id, name, slug, description, is_active, category_id, created_at, updated_at
`

type CreateSubCategoryParams struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	Description sql.NullString
	IsActive    bool
	CategoryID  uuid.UUID
}

func (q *Queries) CreateSubCategory(ctx context.Context, arg CreateSubCategoryParams) (SubCategory, error) {
	row := q.db.QueryRowContext(ctx, createSubCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsActive,
		arg.CategoryID,
	)
	var i SubCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
